# Generated by Django 4.1 on 2023-10-20 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex_type', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('birth_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.')),
            ],
        ),
    ]
